version: '3'

services:
  postgres:
    image: postgres
    container_name: kafka-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kafka-data
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: always
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:5.4.0
    container_name: kafka-server
    depends_on:
      - zookeeper
    environment:
      KAFKA_KAFKA_CLUSTER_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    volumes:
      - ./kafka:/var/lib/kafka/data
    restart: always
    networks:
      - kafka-net

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    container_name: kafka-schema-registry
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    ports:
      - "8081:8081"
    restart: always
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
